<?php
include 'conn.php';
require_once('tcpdf_includea2l.php');
ini_set('max_execution_time', 900);

ob_start();
set_time_limit(0);

ini_set('memory_limit', '-1');
//error_reporting(0);

session_start();
	$ses_user=$_SESSION['login_user'];
	$ses_ulevel=$_SESSION['user_level'];
	$ses_ukey=$_SESSION['user_keye'];
	
$cur_dte=date("Y-m-d");


if(isset($_POST['btn_summeryinvoicecomplete'])){
	$stdte=$_POST['txt_stdte'];
	$enddte=$_POST['txt_enddte'];
	
	
	if($stdte==null || $enddte==null){
		header("location:../../complete_invoicemenu.php");
	}
	else if($stdte>$enddte){
		echo "<script>
			alert('Invalid Date Selection');
			window.location.href='../../complete_invoicemenu.php';
		</script>";
	}
	else{
		
class MYPDF extends TCPDF {

	//Page header
	public function Header() {
		// Logo

		
			$this->SetFont('times', 'B', 20);
			
						//<tr>
						   //<td><h5 align="center"> Progress Summary Sheet </h5> </td>
						//</tr>
			$html ='<table border="0">
						<tr>
							<td width="30%"></td>
							<td width="40%"><h2 align="center" style="color:#001f4d"> Thushans Carrera Motors </h2> </td>
							<td width="30%"></td>
						</tr>';
					
							$html.= '<tr>
								<td width="30%"></td>
								<td width="40%" style="color:#001f4d"><h3 align="center">Complete Invoice </h3> </td>
							   <td width="30%" style="color:#001f4d"><h5 align="right"> Complete Invoice Report </h5></td>
							 </tr>';
							$html.='<tr>
						  <td width="30%"></td>
						   <td width="40%"><h3 align="center" style="color:#001f4d"></h3> </td>
						    <td width="30%"><h6 align="right" style="color:#001f4d"> '.$_POST['txt_stdte'].' to '.$_POST['txt_enddte'].'</h5></td>
						</tr>';
						
				$html.='</table>
				<hr>
				';
			$this->writeHTML($html, true, false, true, false, '');
			// Title
	  
	}
		public function Footer() {
			$ftext='<hr><table border="0" width="100%">
						<tr>
							<td width="40%">'.$_SESSION['login_user'].'</td>
							
							<td width="60%" align="right">Report Generated by Service System &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages().'</td>
						</tr>
						
					</table>';
        // Position at 15 mm from bottom
        $this->SetY(-8);
        // Set font
        $this->SetFont('times', 'I', 12);
        // Page number
		$this->writeHTML($ftext, true, false, true, false, '');
    }
}
// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);

$pdf->SetTitle('Complete Invoices');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// set default header data


// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, 40, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
	require_once(dirname(__FILE__).'/lang/eng.php');
	$pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
$pdf->SetFont('times', '', 15);

// add a page
$pdf->AddPage();
	
	$html='<table border="1">
			<thead>
				<tr style="background-color:#DCDCDC;" align="center">
					<th> <b>No</b></th>
					<th> <b>Invoice No</b></th>
					<th> <b>Date</b></th>
					<th> <b>Vehicle No</b></th>
					<th> <b>Customer Name</b></th>
					<th> <b>Contact No</b></th>
					<th> <b>ODO Meter</b></th>
					<th> <b>Note</b></th>
					<th> <b>Total Amount</b></th>
					<th> <b>Discount</b></th>
					<th> <b>Net Amount</b></th>
					<th> <b>Payment</b></th>
				</tr>
			</thead>
			<tbody>';
			
	$i_totamu=0;
	$i_totdis=0;
	$i_totnet=0;
	$i_totpay=0;
	$i_no=0;
	
	$sql1="SELECT * FROM service_master INNER JOIN vehical_cus_master 
					ON service_master.vehicus_key=vehical_cus_master.vehicus_master_key
				WHERE service_master.date>='$stdte' AND 
					service_master.date<='$enddte' AND 
					service_master.finish_status=1 AND
					service_master.finact=0 
					ORDER BY service_master.date ASC";
	$result1 = mysqli_query($link ,$sql1);
	while($row1=mysqli_fetch_array($result1)){
		$i_no++;
		$html.='<tr>';
			$html.='<td align="right"> '.$i_no.'</td>';
			$html.='<td> '.sprintf('%05d',$row1['servicemaster_key']).'</td>';
			$html.='<td> '.$row1['date'].'</td>';
			$html.='<td> '.$row1['vehical_no'].'</td>';
			$html.='<td> '.$row1['cus_nme'].'</td>';
			$html.='<td> '.$row1['contactno'].'</td>';
			$html.='<td> '.$row1['odo_meter'].'</td>';
			$html.='<td> '.$row1['note'].'</td>';
			$html.='<td align="right">'.number_format($row1['total_amount'],2).'</td>';
			$html.='<td align="right">'.number_format($row1['item_discount'],2).'</td>';
			$html.='<td align="right">'.number_format($row1['afteritemdiscounta_amount'],2).'</td>';
			$html.='<td align="right">'.number_format($row1['payment'],2).'</td>';
						
						
			$i_totamu=$i_totamu+$row1['total_amount'];
			$i_totdis=$i_totdis+$row1['item_discount'];
			$i_totnet=$i_totnet+$row1['afteritemdiscounta_amount'];
			$i_totpay=$i_totpay+$row1['payment'];
					
				
			
		$html.='</tr>';
	}
	
					$html.='<tr style="font-size:18px;font-weight:bold;background-color:#DCDCDC;">';	
						$html.='<td colspan="8"> Total</td>';
						$html.='<td align="right">'.number_format($i_totamu,2).'</td>';
						$html.='<td align="right">'.number_format($i_totdis,2).'</td>';
						$html.='<td align="right">'.number_format($i_totnet,2).'</td>';
						$html.='<td align="right">'.number_format($i_totpay,2).'</td>';
					$html.='</tr>';	
					
		
	$html.='</tbody>
	</table>';
	
	$pdf->writeHTML($html, true, false, true, false, '');

// ---------------------------------------------------------

//Close and output PDF document
$pdf->Output('Complete_Invoice_'.$stdte.'_'.$enddte.'.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+
}
}
?>